### ISSUE TITLE
Error: spawn yarn ENOENT

### ISSUE THREAD

**Issue by Winwardo** [ericclemmons/codelift#49]
Hey,
I'm running on Windows, Node 13.2.0, and cannot start codelift.
This happens whether I use `yarn` or `npm`, same error.

I believe this is a Windows error - you can see other people with a similar issue here:

https://github.com/fusionjs/fusion-scaffolder/issues/46
https://stackoverflow.com/questions/37459717/error-spawn-enoent-on-windows
https://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js

Looks like changing `spawn` to `cross-spawn` in `codelift.js` should fix the issue :)

https://github.com/ericclemmons/codelift/blob/b36da347fd5738dd640d60fee544102e2889b4bd/packages/codelift/bin/codelift.js

The project looks really cool! Can't wait to try it out 👍

```
PS C:\Users\chwinwar\Documents\GitHub\financier> yarn codelift
yarn run v1.21.1
$ C:\Users\chwinwar\Documents\GitHub\financier\node_modules\.bin\codelift
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:262:19)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:12)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn yarn',
  path: 'yarn',
  spawnargs: [ 'start' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ericclemmons** [comment]
@Winwardo You're right on!  I'll switch to `cross-spawn`.

**Comment by dance2die** [comment]
The workaround for that for me was to use `bash` for WSL (Windows Subsystem for Linux).
But if `cross-spawn` is used, this would be non-issue 😉

![McChUWk9cX](https://user-images.githubusercontent.com/8465237/70750201-f15d1600-1cfb-11ea-8051-e5aa87f47e37.gif)

**Comment by ericclemmons** [comment]
Try out `v0.3.2`!

**Comment by dance2die** [comment]
Works for me well @ericclemmons 🤜
