### ISSUE TITLE
craco support

### ISSUE THREAD

**Issue by justinobney** [ericclemmons/codelift#50]
I use [craco](https://github.com/gsoft-inc/craco) to override my create-react-app config, but it requires me to give them control of starting my app via `craco start` similar to how codelift works. I suspect it would be pretty easy to create a `craco-codelift` package. Could you provide some insight into this?

**Comment by justinobney** [comment]
So at first glance, I just needed to:

- `yarn add codelift --dev`
- add `import "codelift/register";` to app
- put the following in my `craco.config.js`:

```js
whenDev(() => {
  require('codelift/server');
});
```

And it appears to sort of work. However, it doesn't quite see my dom properly. It stops after the first 2 `div`'s

![image](https://user-images.githubusercontent.com/1054188/70746633-c8348980-1ceb-11ea-8e9c-a0db728e931b.png)

I did attempt to just start it in a non-trivial app that uses emotion for most styles, so I imagine my configuration is causing a lot of the issues.

**Comment by ericclemmons** [comment]
`codelift` basically does what you noticed: `require('./server')` and runs `yarn $1`.

In your case, do you have a `start` or `dev` script that runs `craco start`?  If so, you could still run `codelift start`, which would run `yarn start` -> `craco start`.  (That's all `codelift` does: starts the server and spawns the `yarn` script as usual, using `start` if not provided).

Let me know if you still see the same thing with this approach (you likely will).  

I've never heard of `craco` before, to be honest.  One of the constraints of this project is that I depend on the Babel plugins that ship with CRA & Next.js to work.

**Comment by ericclemmons** [comment]
I'm investigating this a bit in the Parcel example (#60), but there will likely be constraints requiring CRA/Next with TypeScript support for until `v1.0` is cut.

Thanks for bringing `craco` to my attention! ⭐
