### ISSUE TITLE
configurable port

### ISSUE THREAD

**Issue by sw-yx** [ericclemmons/codelift#51]
by default you wait for `3000`, but sometimes i have other ports like `1234` (parcel)

**Comment by ericclemmons** [comment]
Great point!  I knew this day would come :D

**Comment by ericclemmons** [comment]
Going to likely resolve this with #52.

**Comment by ericclemmons** [comment]
Going to likely resolve this with #52.

**Comment by ericclemmons** [comment]
I may end up recommending adding `--port 3000` the `package.json#scripts` via docs.

`PORT=3000` is convention, so I could possibly key off of that for what to listen to as well.

🤔

**Comment by ericclemmons** [comment]
Since `codelift` calls out to `yarn ...`, the NPM script should be able to handle the `--port 3000` option (as seen in #60).

CRA & Next both do a good job of defaulting to `3000`.

**Comment by ericclemmons** [comment]
Closing via the Parcel example (#60)
