### ISSUE TITLE
Error: http://localhost:1337 fails to open on Windows 10

### ISSUE THREAD

**Issue by dance2die** [ericclemmons/codelift#53]
On Windows 10
Due to 'Error: spawn yarn ENOENT #49' issue, I started the process `yarn codelift start` (for a CRA project) using `bash` for WSL (Windows Subsystem for Linux).

The process starts, but I see the following popup.

![error](https://user-images.githubusercontent.com/8465237/70750413-5f094200-1cfc-11ea-9ecc-3b1cfc54e6ca.png)

You can still manually open `http://localhost:1337`, which works, by the way.

![image](https://user-images.githubusercontent.com/8465237/70750704-e3f45b80-1cfc-11ea-811c-0c4c8ac4100d.png)

---

## Additional Info

**Node Version**:  v12.13.0
**Windows Version**: 
![image](https://user-images.githubusercontent.com/8465237/70750578-a7286480-1cfc-11ea-9150-a954424fe86e.png)

**Comment by ericclemmons** [comment]
Give `v0.3.1` a shot and let me know if #56 resolved it!

**Comment by dance2die** [comment]
It's fixed! (& seems to start faster too).

Thank you @ericclemmons ✋
