### ISSUE TITLE
GitHub organization

### ISSUE THREAD

**Issue by kognise** [ericclemmons/codelift#54]
I propose creating a GitHub organization for Codelift-related repositories. One benefit this would bring is the ability to put examples in their own repos so they can be easily cloned. In the future as Codelift grows it would also bring the possibility of splitting modules out into their own repos, and enable finer-grained access controls.

Although it may seem counter-intuitive to suggest this for a relatively new project in my opinion it's beneficial to do this sooner rather than later.

**Comment by ericclemmons** [comment]
Let's see what sort of legs this project has.  I'm a fan of how Next.js solves examples:
> https://github.com/zeit/next.js/tree/master/examples

If & when we get to that point, transferring ownership to an org (with redirects, too) is a cinch!
