### ISSUE TITLE
I'm interested in contributing.

### ISSUE THREAD

**Issue by shahzeb1** [ericclemmons/codelift#55]
Hello. This looks like an extremely promising project. I was wondering if admins of the repo could tag any potential issues that come up with a "contributor needed" (or similar) tag so I could get involved.

Thank you.

**Comment by ericclemmons** [comment]
@shahzeb1 No tag needed!  If there are any issues you'd like to open or contribute to, simply comment on it with what you'd like to do, just so that you don't do heavy lifting on something that might be changing :D
